/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.librarymanagment;

import java.awt.Color;
import javax.swing.JOptionPane;
import projectdb.ConnectionProvider;
import java.sql.*;
import net.proteanit.sql.DbUtils;
import java.util.*;

/**
 *
 * @author Coco
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addtab = new javax.swing.JButton();
        viewtab = new javax.swing.JButton();
        edittab = new javax.swing.JButton();
        issuetab = new javax.swing.JButton();
        returntab = new javax.swing.JButton();
        logouttab = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        addbook = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addTitle = new javax.swing.JTextField();
        addAuthor = new javax.swing.JTextField();
        addISBN = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addDESC = new javax.swing.JTextArea();
        addBook = new javax.swing.JButton();
        viewbook = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        viewSearchby = new javax.swing.JComboBox<>();
        viewSearch = new javax.swing.JTextField();
        viewSearchbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        viewtitle = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        viewauthor = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        viewisbn = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewdisc = new javax.swing.JTextArea();
        returnbook = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        returnTable = new javax.swing.JTable();
        returnBtn = new javax.swing.JButton();
        returnid = new javax.swing.JLabel();
        issue_book = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        issuetable = new javax.swing.JTable();
        issueSearchBy = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        issueSearchTf = new javax.swing.JTextField();
        issueSearchBtn = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        studentName = new javax.swing.JTextField();
        studentId = new javax.swing.JTextField();
        membershipId = new javax.swing.JTextField();
        IssueDate = new com.toedter.calendar.JDateChooser();
        issueBtn = new javax.swing.JButton();
        issueID = new javax.swing.JLabel();
        editbook = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        editSearchby = new javax.swing.JComboBox<>();
        editSearchTf = new javax.swing.JTextField();
        editSearchbtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        editTable = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        editTitle = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        editAuthor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        editISBN = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        editDESC = new javax.swing.JTextArea();
        editbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        editID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(120, 149, 203));

        addtab.setBackground(new java.awt.Color(74, 85, 162));
        addtab.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        addtab.setText("Add books");
        addtab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtabActionPerformed(evt);
            }
        });

        viewtab.setBackground(new java.awt.Color(74, 85, 162));
        viewtab.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        viewtab.setText("View books");
        viewtab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewtabActionPerformed(evt);
            }
        });

        edittab.setBackground(new java.awt.Color(74, 85, 162));
        edittab.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        edittab.setText("Edit/delete");
        edittab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edittabActionPerformed(evt);
            }
        });

        issuetab.setBackground(new java.awt.Color(74, 85, 162));
        issuetab.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        issuetab.setText("Issue book");
        issuetab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuetabActionPerformed(evt);
            }
        });

        returntab.setBackground(new java.awt.Color(74, 85, 162));
        returntab.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        returntab.setText("Return Book");
        returntab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returntabActionPerformed(evt);
            }
        });

        logouttab.setBackground(new java.awt.Color(74, 85, 162));
        logouttab.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        logouttab.setText("Logout");
        logouttab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logouttabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logouttabMouseExited(evt);
            }
        });
        logouttab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logouttabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(addtab)
                .addGap(40, 40, 40)
                .addComponent(viewtab)
                .addGap(37, 37, 37)
                .addComponent(edittab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(issuetab)
                .addGap(43, 43, 43)
                .addComponent(returntab)
                .addGap(31, 31, 31)
                .addComponent(logouttab)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addtab, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewtab, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edittab, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logouttab, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issuetab, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returntab, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jPanel2.setBackground(new java.awt.Color(225, 236, 200));
        jPanel2.setLayout(new java.awt.CardLayout());

        addbook.setBackground(new java.awt.Color(160, 191, 224));

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        jLabel1.setText("Book Title");

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        jLabel2.setText("Author");

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        jLabel3.setText("ISBN");

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        jLabel4.setText("Description ");

        addTitle.setBackground(new java.awt.Color(197, 223, 248));
        addTitle.setText(" ");

        addAuthor.setBackground(new java.awt.Color(197, 223, 248));
        addAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAuthorActionPerformed(evt);
            }
        });

        addISBN.setBackground(new java.awt.Color(197, 223, 248));
        addISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addISBNActionPerformed(evt);
            }
        });

        addDESC.setBackground(new java.awt.Color(197, 223, 248));
        addDESC.setColumns(20);
        addDESC.setLineWrap(true);
        addDESC.setRows(5);
        jScrollPane1.setViewportView(addDESC);

        addBook.setBackground(new java.awt.Color(74, 85, 162));
        addBook.setFont(new java.awt.Font("OCR A Extended", 1, 13)); // NOI18N
        addBook.setText("Add book");
        addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addbookLayout = new javax.swing.GroupLayout(addbook);
        addbook.setLayout(addbookLayout);
        addbookLayout.setHorizontalGroup(
            addbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbookLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(addbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(addbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addBook, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        addbookLayout.setVerticalGroup(
            addbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addbookLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(addAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(addISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(addBook)
                .addGap(82, 82, 82))
        );

        jPanel2.add(addbook, "card2");

        viewbook.setBackground(new java.awt.Color(160, 191, 224));

        jLabel5.setText("Search by");

        viewSearchby.setBackground(new java.awt.Color(197, 223, 248));
        viewSearchby.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "title", "author", "isbn" }));

        viewSearch.setBackground(new java.awt.Color(197, 223, 248));
        viewSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSearchActionPerformed(evt);
            }
        });

        viewSearchbtn.setBackground(new java.awt.Color(74, 85, 162));
        viewSearchbtn.setFont(new java.awt.Font("OCR A Extended", 1, 13)); // NOI18N
        viewSearchbtn.setForeground(new java.awt.Color(255, 255, 255));
        viewSearchbtn.setText("Search");
        viewSearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSearchbtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("Book Title");

        viewtitle.setText("[none]");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setText("Author");

        viewauthor.setText("[none]");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setText("ISBN");

        viewisbn.setText("[none]");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel12.setText("Description");

        jTable3.setBackground(new java.awt.Color(197, 223, 248));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setGridColor(new java.awt.Color(255, 255, 255));
        jTable3.setSelectionBackground(new java.awt.Color(102, 204, 255));
        jTable3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable3FocusLost(evt);
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jTable3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable3ComponentShown(evt);
            }
        });
        jScrollPane5.setViewportView(jTable3);

        viewdisc.setEditable(false);
        viewdisc.setBackground(new java.awt.Color(197, 223, 248));
        viewdisc.setColumns(20);
        viewdisc.setLineWrap(true);
        viewdisc.setRows(5);
        viewdisc.setWrapStyleWord(true);
        jScrollPane2.setViewportView(viewdisc);

        javax.swing.GroupLayout viewbookLayout = new javax.swing.GroupLayout(viewbook);
        viewbook.setLayout(viewbookLayout);
        viewbookLayout.setHorizontalGroup(
            viewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewbookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewbookLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(viewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewisbn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(viewbookLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewSearchby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(viewSearchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        viewbookLayout.setVerticalGroup(
            viewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewbookLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(viewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(viewSearchby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewSearchbtn))
                .addGap(32, 32, 32)
                .addGroup(viewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(viewbookLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewtitle)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewauthor)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewisbn)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel2.add(viewbook, "card2");

        returnbook.setBackground(new java.awt.Color(160, 191, 224));

        jLabel11.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel11.setText("Issued books");

        returnTable.setBackground(new java.awt.Color(197, 223, 248));
        returnTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        returnTable.setSelectionBackground(new java.awt.Color(102, 204, 255));
        returnTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(returnTable);

        returnBtn.setBackground(new java.awt.Color(74, 85, 162));
        returnBtn.setFont(new java.awt.Font("OCR A Extended", 1, 13)); // NOI18N
        returnBtn.setForeground(new java.awt.Color(255, 255, 255));
        returnBtn.setText("Returned");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        returnid.setText("#");

        javax.swing.GroupLayout returnbookLayout = new javax.swing.GroupLayout(returnbook);
        returnbook.setLayout(returnbookLayout);
        returnbookLayout.setHorizontalGroup(
            returnbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnbookLayout.createSequentialGroup()
                .addGroup(returnbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnbookLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(returnbookLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(returnbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(returnbookLayout.createSequentialGroup()
                                .addComponent(returnid)
                                .addGap(194, 194, 194)
                                .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        returnbookLayout.setVerticalGroup(
            returnbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnbookLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(returnbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnid))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jPanel2.add(returnbook, "card6");

        issue_book.setBackground(new java.awt.Color(160, 191, 224));

        issuetable.setBackground(new java.awt.Color(197, 223, 248));
        issuetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        issuetable.setGridColor(new java.awt.Color(255, 255, 255));
        issuetable.setSelectionBackground(new java.awt.Color(102, 204, 255));
        issuetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issuetableMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(issuetable);

        issueSearchBy.setBackground(new java.awt.Color(197, 223, 248));
        issueSearchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "title", "author", "isbn" }));

        jLabel13.setText("Search by");

        issueSearchTf.setBackground(new java.awt.Color(197, 223, 248));
        issueSearchTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueSearchTfActionPerformed(evt);
            }
        });

        issueSearchBtn.setBackground(new java.awt.Color(74, 85, 162));
        issueSearchBtn.setFont(new java.awt.Font("OCR A Extended", 1, 13)); // NOI18N
        issueSearchBtn.setForeground(new java.awt.Color(255, 255, 255));
        issueSearchBtn.setText("Search");
        issueSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueSearchBtnActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Student name");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Student ID");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("membership ID");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Issue date");

        studentName.setBackground(new java.awt.Color(197, 223, 248));

        studentId.setBackground(new java.awt.Color(197, 223, 248));

        membershipId.setBackground(new java.awt.Color(197, 223, 248));

        IssueDate.setBackground(new java.awt.Color(197, 223, 248));
        IssueDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IssueDateMouseClicked(evt);
            }
        });

        issueBtn.setBackground(new java.awt.Color(74, 85, 162));
        issueBtn.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        issueBtn.setForeground(new java.awt.Color(255, 255, 255));
        issueBtn.setText("Issue book");
        issueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBtnActionPerformed(evt);
            }
        });

        issueID.setText("#");

        javax.swing.GroupLayout issue_bookLayout = new javax.swing.GroupLayout(issue_book);
        issue_book.setLayout(issue_bookLayout);
        issue_bookLayout.setHorizontalGroup(
            issue_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issue_bookLayout.createSequentialGroup()
                .addGroup(issue_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(issue_bookLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(issue_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(issue_bookLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(issue_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(issueID)
                                    .addGroup(issue_bookLayout.createSequentialGroup()
                                        .addGroup(issue_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(issue_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(studentName)
                                            .addComponent(studentId)
                                            .addComponent(membershipId)
                                            .addComponent(IssueDate, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))))
                            .addGroup(issue_bookLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(issueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(issue_bookLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(issueSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(issueSearchTf, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(issueSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        issue_bookLayout.setVerticalGroup(
            issue_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issue_bookLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(issue_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issueSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(issueSearchTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issueSearchBtn))
                .addGroup(issue_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(issue_bookLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(issue_bookLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(issueID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(issue_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(issue_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(studentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(issue_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(membershipId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(issue_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(IssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addComponent(issueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel2.add(issue_book, "card5");

        editbook.setBackground(new java.awt.Color(160, 191, 224));
        editbook.setName("Addbook"); // NOI18N

        jLabel14.setText("Search by");

        editSearchby.setBackground(new java.awt.Color(197, 223, 248));
        editSearchby.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Title", "Author", "ISBN" }));

        editSearchTf.setBackground(new java.awt.Color(197, 223, 248));

        editSearchbtn.setBackground(new java.awt.Color(74, 85, 162));
        editSearchbtn.setFont(new java.awt.Font("OCR A Extended", 1, 13)); // NOI18N
        editSearchbtn.setForeground(new java.awt.Color(255, 255, 255));
        editSearchbtn.setText("Search");
        editSearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSearchbtnActionPerformed(evt);
            }
        });

        editTable.setBackground(new java.awt.Color(197, 223, 248));
        editTable.setRowHeight(25);
        editTable.setSelectionBackground(new java.awt.Color(102, 204, 255));
        editTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(editTable);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Book title");

        editTitle.setBackground(new java.awt.Color(197, 223, 248));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Author");

        editAuthor.setBackground(new java.awt.Color(197, 223, 248));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("ISBN");

        editISBN.setBackground(new java.awt.Color(197, 223, 248));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Description");

        editDESC.setBackground(new java.awt.Color(197, 223, 248));
        editDESC.setColumns(20);
        editDESC.setLineWrap(true);
        editDESC.setRows(5);
        jScrollPane4.setViewportView(editDESC);

        editbtn.setBackground(new java.awt.Color(74, 85, 162));
        editbtn.setFont(new java.awt.Font("OCR A Extended", 1, 13)); // NOI18N
        editbtn.setForeground(new java.awt.Color(255, 255, 255));
        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        deletebtn.setBackground(new java.awt.Color(74, 85, 162));
        deletebtn.setFont(new java.awt.Font("OCR A Extended", 1, 13)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(255, 255, 255));
        deletebtn.setText("Delete");
        deletebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deletebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deletebtnMouseExited(evt);
            }
        });
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setText("ID ");

        editID.setText("#");

        javax.swing.GroupLayout editbookLayout = new javax.swing.GroupLayout(editbook);
        editbook.setLayout(editbookLayout);
        editbookLayout.setHorizontalGroup(
            editbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editbookLayout.createSequentialGroup()
                .addGroup(editbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editbookLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editbookLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(editSearchby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(editSearchTf, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editSearchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editbookLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(editbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editbookLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(editbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(editbookLayout.createSequentialGroup()
                                        .addGroup(editbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(editbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(editbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(editTitle)
                                                .addComponent(editAuthor)
                                                .addComponent(editISBN, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                                            .addComponent(editID, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(editbookLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(editbtn))
                            .addGroup(editbookLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        editbookLayout.setVerticalGroup(
            editbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editbookLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(editbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(editSearchby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editSearchTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editSearchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(editbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editbookLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(editbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(editID))
                        .addGap(18, 18, 18)
                        .addGroup(editbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(editTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(editbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(editAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(editbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(editISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(editbtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editbookLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deletebtn)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel2.add(editbook, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewtabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewtabActionPerformed
            jPanel2.removeAll();
            jPanel2.add(viewbook);
            jPanel2.repaint();
            jPanel2.revalidate();    
            

try{
    Connection con = ConnectionProvider.getcon();

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select id,title,author,isbn from book;");

            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
            
   
}catch(Exception e){
   
}


// TODO add your handling code here:
    }//GEN-LAST:event_viewtabActionPerformed

    private void edittabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edittabActionPerformed
jPanel2.removeAll();
            jPanel2.add(editbook);
            jPanel2.repaint();
            jPanel2.revalidate(); 
            
try{
    Connection con = ConnectionProvider.getcon();

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select id,title,author,isbn from book;");

            editTable.setModel(DbUtils.resultSetToTableModel(rs));
            
   
}catch(Exception e){
   
}




// TODO add your handling code here:
    }//GEN-LAST:event_edittabActionPerformed

    private void addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookActionPerformed
        String title = addTitle.getText();
        String author = addAuthor.getText();
        String isbn = addISBN.getText();
        String desc = addDESC.getText();
        
        
        
        if(title.equals("")||author.equals("")||desc.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill all the required information");
        }else if(validate.validateISBN(isbn)){
            JOptionPane.showMessageDialog(null,"Invalid ISBN");    
        }else if(desc.length()>250){
            JOptionPane.showMessageDialog(null,"Description too long. must be less than 250 characters");
        }else{
            try{
            Connection con = ConnectionProvider.getcon();
            Statement st = con.createStatement();
            int update=0;
            
            boolean book_exist = false;
            String sql = "select title,author,isbn from book;";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                if((rs.getString(1)==title&&rs.getString(2)==author)||(rs.getString(3)==isbn)){
                    book_exist=true;
                }
            }
            
        
                if(!book_exist){
                    String in = "insert into book(title,author,isbn,disc) values('"+title+"','"+author+"','"+isbn+"','"+desc+"');";
                    
                    update = st.executeUpdate(in);
                    addTitle.setText("");
                    addAuthor.setText("");
                    addISBN.setText("");
                    addDESC.setText("");
                  JOptionPane.showMessageDialog(null, "Book successfully added");
                  
                  
                }
            if(update==0){
                JOptionPane.showMessageDialog(null, "The entry already exist.");
            }
            con.close();
        }catch(Exception e){
              
                }

        // TODO add your handling code here:
    }//GEN-LAST:event_addBookActionPerformed
    }
    private void editSearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSearchbtnActionPerformed


    String search = editSearchTf.getText();
    String searchby = editSearchby.getSelectedItem().toString();
    
    try{
        Connection con = ConnectionProvider.getcon();
        Statement st = con.createStatement();
        String sql = "select id,title,author,isbn from book where "+searchby+"='"+search+"';";
        ResultSet rs = st.executeQuery(sql);
        editTable.setModel(DbUtils.resultSetToTableModel(rs));
        con.close();
        
        
        
    }catch(Exception e)
    {
        
    }

        
        
        
   
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        

        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_editSearchbtnActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        
        
        String id = editID.getText();
        String title = editTitle.getText();
        String author = editAuthor.getText();
        String isbn = editISBN.getText();
        String disc = editDESC.getText();
        
        if(!(Character.isDigit(id.charAt(0)))){
            JOptionPane.showMessageDialog(null, "Please choose a book!");
        }else if(title.equals("")||author.equals("")||isbn.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill the required fields!");
        }else if(validate.validateISBN(isbn)){
            JOptionPane.showMessageDialog(null, "Invalid ISBN!");
        }else if(disc.length()>250){
            JOptionPane.showMessageDialog(null, "Description must be less than 250 characters.");
        }else{
            
            try{
               
                
                Connection con = ConnectionProvider.getcon();
                Statement st = con.createStatement();
                String sql = "update book set title='"+title+"',author='"+author+"',isbn='"+isbn+"', disc='"+disc+"' where id="+id+";";
                int update = st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Edit success!");
                
            
            ResultSet rs = st.executeQuery("select id,title,author,isbn from book;");

            editTable.setModel(DbUtils.resultSetToTableModel(rs));
            }catch(Exception e){
                
                
            }
            
            
            
        }
        
        
        
        
        
        
        
        
        
        
 
        // TODO add your handling code here:
    }//GEN-LAST:event_editbtnActionPerformed

    private void addAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addAuthorActionPerformed

    private void addISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addISBNActionPerformed

    private void addtabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtabActionPerformed
jPanel2.removeAll();
            jPanel2.add(addbook);
            jPanel2.repaint();
            jPanel2.revalidate();         // TODO add your handling code here:
    }//GEN-LAST:event_addtabActionPerformed

    private void jTable3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable3ComponentShown

        try{
            Connection con = ConnectionProvider.getcon();

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select id,title,author,isbn from book;");
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3ComponentShown

    private void viewSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewSearchActionPerformed

    private void viewSearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSearchbtnActionPerformed
        String search = viewSearch.getText();
        String Searchby = viewSearchby.getSelectedItem().toString();
        try{
    Connection con = ConnectionProvider.getcon();
    Statement st = con.createStatement();
    String sql = "select id,title,author,isbn from book where "+Searchby+"='"+search+"';";
    ResultSet rs = st.executeQuery(sql);
    jTable3.removeAll();
    jTable3.setModel(DbUtils.resultSetToTableModel(rs));
   con.close();
    
    
}catch(Exception e){
    
}
        // TODO add your handling code here:
    }//GEN-LAST:event_viewSearchbtnActionPerformed

    private void jTable3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable3FocusGained
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3FocusGained

    private void jTable3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable3FocusLost
            
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3FocusLost

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        int row = jTable3.rowAtPoint(evt.getPoint());

        try{
            Connection con = ConnectionProvider.getcon();
            Statement st = con.createStatement();
            String sql = "select * from book where title ='"+jTable3.getValueAt(row, 1).toString()+"';";
            ResultSet rs = st.executeQuery(sql);
            rs.next();
        viewtitle.setText(rs.getString(2));
        viewauthor.setText(rs.getString(3));
        viewisbn.setText(rs.getString(4));
        viewdisc.setText(rs.getString(5));
            
            
        }catch(Exception e){
            
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseClicked

    private void editTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editTableMouseClicked
        int row = editTable.rowAtPoint(evt.getPoint());
        
        
        try{
            Connection con = ConnectionProvider.getcon();
            Statement st = con.createStatement();
            String sql = "select * from book where title ='"+editTable.getValueAt(row, 1).toString()+"';";
            ResultSet rs = st.executeQuery(sql);
            rs.next();
        editID.setText(rs.getString(1));
        editTitle.setText(rs.getString(2));
        editAuthor.setText(rs.getString(3));
        editISBN.setText(rs.getString(4));
        editDESC.setText(rs.getString(5));
            
            
        }catch(Exception e){
            
        }



        // TODO add your handling code here:
    }//GEN-LAST:event_editTableMouseClicked

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed


        String id = editID.getText();
        int del=JOptionPane.showConfirmDialog(null,"Are you sure you want to delete "+editTitle.getText()+" by "+editAuthor.getText()+"?");  
if(del==JOptionPane.YES_OPTION){  
    try{  
        Connection con= ConnectionProvider.getcon();
        Statement st = con.createStatement();
        String sql = "delete from book where id="+id+";";
        boolean a = st.execute(sql);
        JOptionPane.showMessageDialog(null, "Delete Success!");
        ResultSet rs = st.executeQuery("select id,title,author,isbn from book;");
        editTable.setModel(DbUtils.resultSetToTableModel(rs));
        con.close();
        
     
    }catch(Exception e)
    {
        
    }
}  

        // TODO add your handling code here:
    }//GEN-LAST:event_deletebtnActionPerformed

    private void returntabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returntabActionPerformed
jPanel2.removeAll();
            jPanel2.add(returnbook);
            jPanel2.repaint();
            jPanel2.revalidate();   
            
try{
    Connection con = ConnectionProvider.getcon();

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select id,book_title,book_author,book_isbn,student_name,student_id,student_membership_id,issue_date from issuedbooks;");

            returnTable.setModel(DbUtils.resultSetToTableModel(rs));
            
   
}catch(Exception e){
   
    
}




// TODO add your handling code here:
    }//GEN-LAST:event_returntabActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed

        int a = JOptionPane.showConfirmDialog(null, "Confirm the return");
        if(a==JOptionPane.YES_OPTION){
            try{
                Connection con = ConnectionProvider.getcon();
                Statement st = con.createStatement();
                String sql = "delete from issuedbooks where id="+returnid.getText()+";";
                boolean update= st.execute(sql);
                
                
            ResultSet rs = st.executeQuery("select id,book_title,book_author,book_isbn,student_name,student_id,student_membership_id,issue_date from issuedbooks;");

            returnTable.setModel(DbUtils.resultSetToTableModel(rs));
                con.close();
            }catch(Exception e){
                
            }
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_returnBtnActionPerformed

    private void issueSearchTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueSearchTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issueSearchTfActionPerformed

    private void issuetabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuetabActionPerformed
jPanel2.removeAll();
            jPanel2.add(issue_book);
            jPanel2.repaint();
            jPanel2.revalidate(); 
            
            try{
    Connection con = ConnectionProvider.getcon();

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select id,title,author,isbn from book;");

            issuetable.setModel(DbUtils.resultSetToTableModel(rs));
            
   
}catch(Exception e){
    
}



// TODO add your handling code here:
    }//GEN-LAST:event_issuetabActionPerformed

    private void logouttabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logouttabActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?");
        if(a==JOptionPane.YES_OPTION){
            new login().setVisible(true);
                setVisible(false);
            
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_logouttabActionPerformed

    private void issueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBtnActionPerformed
          
           
                   
        String stname = studentName.getText();
           String stid = studentId.getText();
           String stmid = membershipId.getText();
           java.util.Date dateobj = IssueDate.getDate();
           String date ="";
           if(dateobj!=null){
            date= dateobj.toString();
           }
           
           
           if(!(Character.isDigit(issueID.getText().charAt(0)))){
               JOptionPane.showMessageDialog(null, "Please choose a book");
    
           }else if( stname.equals("")|| stid.equals("")|| stmid.equals("")|| date.equals("")){
               JOptionPane.showMessageDialog(null, "Please fill all the required info");
           }else if(validate.validatename(stname)){
               JOptionPane.showMessageDialog(null, "Student name cant contain numbers!");
           }else{
               try{
                   
                   
                   Connection con = ConnectionProvider.getcon();
                   Statement st = con.createStatement();
                   String sql = "select title, author,isbn from book where id="+issueID.getText()+";";
                  
                   ResultSet rs = st.executeQuery(sql);
                   rs.next();
                   String title = rs.getString(1);
                   
                   String author = rs.getString(2);
                   String isbn = rs.getString(3);
                   
                  String inSQL = "insert into issuedbooks (book_title,book_author,book_isbn,student_name,student_id,student_membership_id,issue_date) values(?,?,?,?,?,?,?);";
                  PreparedStatement pt = con.prepareStatement(inSQL);
                  pt.setString(1,title);
                  pt.setString(2,author);
                  pt.setString(3,isbn);
                  pt.setString(4,stname);
                  pt.setString(5,stid);
                  pt.setString(6,stmid);
                  pt.setString(7,date);
                  
                   boolean a =pt.execute();
                   JOptionPane.showMessageDialog(null, "Book issued successfuly");
           
                   con.close();
                   
               }catch(Exception e){
                   
               }
           }



        // TODO add your handling code here:
    }//GEN-LAST:event_issueBtnActionPerformed

    private void IssueDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IssueDateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_IssueDateMouseClicked

    private void issueSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueSearchBtnActionPerformed

        
            String search = issueSearchTf.getText();
            String searchby = issueSearchBy.getSelectedItem().toString();
            try{
                Connection con= ConnectionProvider.getcon();
                Statement st = con.createStatement();
                    String sql = "select id,title,author,isbn from book where "+searchby+"='"+search+"';";
    ResultSet rs = st.executeQuery(sql);
    issuetable.removeAll();
    issuetable.setModel(DbUtils.resultSetToTableModel(rs));
   con.close();
            }catch(Exception e){
                
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_issueSearchBtnActionPerformed

    private void issuetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issuetableMouseClicked
        int row = issuetable.rowAtPoint(evt.getPoint());       
        issueID.setText((issuetable.getValueAt(issuetable.rowAtPoint(evt.getPoint()), 0)).toString());
        
        
        
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_issuetableMouseClicked

    private void returnTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnTableMouseClicked
int row = returnTable.rowAtPoint(evt.getPoint());
returnid.setText((returnTable.getValueAt(returnTable.rowAtPoint(evt.getPoint()), 0)).toString());
        
        
        try{
            Connection con = ConnectionProvider.getcon();
            Statement st = con.createStatement();
            String sql = "delete from issuedbo where book_title ='"+returnTable.getValueAt(row, 2).toString()+"';";
            ResultSet rs = st.executeQuery(sql);
            rs.next();
        returnid.setText(rs.getString(1));
        
        
        }catch(Exception e){
            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_returnTableMouseClicked

    private void logouttabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logouttabMouseEntered
            logouttab.setBackground(Color.red);


        // TODO add your handling code here:
    }//GEN-LAST:event_logouttabMouseEntered

    private void logouttabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logouttabMouseExited
        logouttab.setBackground(Color.getColor("4A55A2"));

        // TODO add your handling code here:
    }//GEN-LAST:event_logouttabMouseExited

    private void deletebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebtnMouseEntered
   


        // TODO add your handling code here:
    }//GEN-LAST:event_deletebtnMouseEntered

    private void deletebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebtnMouseExited

        
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser IssueDate;
    private javax.swing.JTextField addAuthor;
    private javax.swing.JButton addBook;
    private javax.swing.JTextArea addDESC;
    private javax.swing.JTextField addISBN;
    private javax.swing.JTextField addTitle;
    private javax.swing.JPanel addbook;
    private javax.swing.JButton addtab;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField editAuthor;
    private javax.swing.JTextArea editDESC;
    private javax.swing.JLabel editID;
    private javax.swing.JTextField editISBN;
    private javax.swing.JTextField editSearchTf;
    private javax.swing.JButton editSearchbtn;
    private javax.swing.JComboBox<String> editSearchby;
    private javax.swing.JTable editTable;
    private javax.swing.JTextField editTitle;
    private javax.swing.JPanel editbook;
    private javax.swing.JButton editbtn;
    private javax.swing.JButton edittab;
    private javax.swing.JButton issueBtn;
    private javax.swing.JLabel issueID;
    private javax.swing.JButton issueSearchBtn;
    private javax.swing.JComboBox<String> issueSearchBy;
    private javax.swing.JTextField issueSearchTf;
    private javax.swing.JPanel issue_book;
    private javax.swing.JButton issuetab;
    private javax.swing.JTable issuetable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton logouttab;
    private javax.swing.JTextField membershipId;
    private javax.swing.JButton returnBtn;
    private javax.swing.JTable returnTable;
    private javax.swing.JPanel returnbook;
    private javax.swing.JLabel returnid;
    private javax.swing.JButton returntab;
    private javax.swing.JTextField studentId;
    private javax.swing.JTextField studentName;
    private javax.swing.JTextField viewSearch;
    private javax.swing.JButton viewSearchbtn;
    private javax.swing.JComboBox<String> viewSearchby;
    private javax.swing.JLabel viewauthor;
    private javax.swing.JPanel viewbook;
    private javax.swing.JTextArea viewdisc;
    private javax.swing.JLabel viewisbn;
    private javax.swing.JButton viewtab;
    private javax.swing.JLabel viewtitle;
    // End of variables declaration//GEN-END:variables
}
